# NOTE: This project does not attribute contributors individually. Instead refer to `git log --format="%an <%aE>" | sort -u` for a list of individual contributors.
SPDX-PackageDownloadLocation = "https://gitlab.archlinux.org/archlinux/signstar"
SPDX-PackageName = "signstar"
SPDX-PackageSupplier = "Arch Linux"
version = 1

[[annotations]]
SPDX-FileCopyrightText = "Signstar Contributors"
SPDX-License-Identifier = "Apache-2.0 OR MIT"
path = ["**.rs"]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Signstar Contributors"
SPDX-License-Identifier = "CC0-1.0"
path = [
    "**.toml",
    "*.json",
    ".cargo/runner.sh",
    ".codespellrc",
    ".containers/Containerfile.integration-test",
    ".env",
    ".gitignore",
    ".gitlab-ci.yml",
    ".gitlab/CODEOWNERS",
    ".lycheeignore",
    ".shellcheckrc",
    "Cargo.lock",
    "justfile",
    "lychee.toml",
    "resources/docs/src/api-docs/dependency_graph.png",
    "resources/mkosi/signstar/**.conf",
    "resources/mkosi/signstar/*.chroot",
    "resources/mkosi/signstar/*.env",
    "resources/mkosi/signstar/*.machine-id",
    "resources/mkosi/signstar/*.postinst",
    "resources/mkosi/signstar/*.prepare",
    "resources/mkosi/signstar/*.version",
    "resources/mkosi/signstar/mkosi.extra/etc/kernel/tries",
    "resources/mkosi/signstar/mkosi.extra/etc/machine-id",
    "resources/mkosi/signstar/mkosi.extra/usr/lib/systemd/import-pubring.gpg",
    "resources/mkosi/signstar/mkosi.extra/usr/lib/systemd/network/*.network",
    "resources/mkosi/signstar/mkosi.extra/usr/lib/systemd/system-preset/*.preset",
    "resources/mkosi/signstar/mkosi.extra/usr/lib/systemd/system/*.service",
    "resources/mkosi/signstar/mkosi.output/*.efi",
    "resources/mkosi/signstar/mkosi.output/*.initrd",
    "resources/mkosi/signstar/mkosi.output/*.manifest",
    "resources/mkosi/signstar/mkosi.output/*.raw",
    "resources/mkosi/signstar/mkosi.output/*.vmlinuz",
    "resources/mkosi/signstar/mkosi.output/.gitignore",
    "resources/mkosi/signstar/mkosi.profiles/local-testing/mkosi.extra/usr/local/bin/.gitignore",
    "resources/mkosi/signstar/mkosi.profiles/local-testing/mkosi.extra/usr/local/share/signstar/.gitignore",
    "signstar-crypto/tests/fixtures/*.asc",
    "signstar-request-signature/tests/*.json",
    "signstar-request-signature/tests/sshd/*",
    "signstar-yubihsm2/tests/scenarios/**.json",
    "signstar-yubihsm2/tests/scenarios/keys/*",
]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Signstar Contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0"
path = ["**.md"]
precedence = "aggregate"
