[book]
authors = ["David Runge", "Wiktor Kwapisiewicz"]
language = "en"
src = "src"
title = "Signstar"

[build]
build-dir = "../../output/docs"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid-init.js", "mermaid.min.js"]
git-repository-icon = "fas-code-fork"
git-repository-url = "https://gitlab.archlinux.org/archlinux/signstar"
